### ISSUE TITLE
Volume metrics?

### ISSUE THREAD

**Issue by razvan-ig** [nutanix/csi-plugin#23]
Hello - my understanding of the conversation in https://github.com/google/cadvisor/issues/1702 is there's a debate on where should metrics like `volume_stats_available_bytes` be generated - kubelet or CSI driver; is this something you have considered in this project? If not, is there some related project that collects stats of Nutanix volumes?

**Comment by subodh01** [comment]
Yes, we will be adding support for volume metrics in Nutanix CSI driver in upcoming release.

**Comment by rgarcia89** [comment]
Awesome any idea when it will become available?

**Comment by Mario-F** [comment]
I would also like to see this implemented

**Comment by Mario-F** [comment]
Until this issue is solved i implemented a prometheus pvc-exporter for monitoring pvc usage working with nutanix csi
https://github.com/Mario-F/pvc-exporter

**Comment by subodh01** [comment]
Volume metrics along with CSI operation metrics will come in the next release, sometimes in August.

**Comment by subodh01** [comment]
Volume and CSI operation metrics support is released with Nutanix CSI driver v2.4.1.

**Comment by h-wookie** [comment]
@subodh01 Where can I find sample queries? I already installed csi-provisioner-ntnx-plugin `provisioner`, `resizer`.
Please how can i get metrics from prometheus... 🙏
![image](https://user-images.githubusercontent.com/40632767/150155911-6a292d2f-be7e-4e07-8349-a055c241d275.png)
