### ISSUE TITLE
Copy volume snapshot to different cluster

### ISSUE THREAD

**Issue by razvan-ig** [nutanix/csi-plugin#25]
Hi - to cover DR / migration scenarios, we must have a method of exporting PVs to storage outside the K8s cluster, in a form that can be re-created as VolumeSnapshotClass (as per https://portal.nutanix.com/page/documents/details?targetId=CSI-Volume-Driver-v2_0:csi-csi-driver-create-snapshotpvc-t.html); is such functionality envisaged/planned? If not, a link to Nutanix solutions that cover such a use case would be very welcome!

**Comment by subodh01** [comment]
Presently, I recommend using Velero. https://next.nutanix.com/karbon-kubernetes-orchestration-30/backing-up-karbon-kubernetes-clusters-with-velero-and-nutanix-objects-33513

**Comment by razvan-ig** [comment]
thank you!
