### ISSUE TITLE
v2 release?

### ISSUE THREAD

**Issue by razvan-ig** [nutanix/csi-plugin#26]
The README mentions it and points to docs, images are released at https://hub.docker.com/r/ntnx/ntnx-csi/tags but https://github.com/nutanix/helm/tree/master/charts/nutanix-csi-storage is still 1.1 and this Github project only has it in a branch; is v2 considered ready?

**Comment by subodh01** [comment]
Helm chart for CSI driver is not up to date. @tuxtof 

v2 release of CSI driver is fully supported.

**Comment by razvan-ig** [comment]
thank you!
