### ISSUE TITLE
Upgrade CSI driver process

### ISSUE THREAD

**Issue by san360** [nutanix/csi-plugin#3]
Hey Guys,

Could you please provide documentation for upgrading csi driver?

Thanks
Sanjay

**Comment by subodh01** [comment]
Hi,
CSI driver is stateless. You can remove existing deployment using "kubectl delete -f <yaml-file>" and redeploy using new yaml file "kubectl create -f <yaml-file>".
Existing pod which is using the CSI volume is not impacted unless the pod itself restarts. 

-Subodh

**Comment by san360** [comment]
Thanks for your input. I delete everything and recreated.I am facing another issue now and have opened a issue https://github.com/nutanix/csi-plugin/issues/4

**Comment by subodh01** [comment]
This issue is resolved.
