### ISSUE TITLE
Documentation is missing/not accessible

### ISSUE THREAD

**Issue by romdalf** [nutanix/csi-plugin#30]
The documentation related to the CSI plugin is currently hosted on your Nutanix corporate website requiring valid credentials.
Please provide either a public access to the documentation from your corporate website or via this repository.

**Comment by subodh01** [comment]
You should be able to access https://portal.nutanix.com/page/documents/details?targetId=CSI-Volume-Driver-v2_2:CSI-Volume-Driver-v2_2.

We are in process of making older documents also public.
