### ISSUE TITLE
Typos in documentation / YAML Examples (StorageClass)

### ISSUE THREAD

**Issue by mscbpi** [nutanix/csi-plugin#31]
[Latest 2.1 Doc](https://portal.nutanix.com/page/documents/details?targetId=CSI-Volume-Driver-v2_1:CSI-Volume-Driver-v2_1) has two mistakes in the StorageClass yaml:

`allowVolumeExpand` : it does not exist in api ` storage.k8s.io/v1`. Surely `allowVolumeExpansion`.

`annonations` => `annotations`

**Comment by subodh01** [comment]
Thanks for reporting, I have created internal ticket to track this.
