### ISSUE TITLE
CSI Plugin 2.3.1 - pods not mounting volumes even though PVs are bound

### ISSUE THREAD

**Issue by ccaprusu** [nutanix/csi-plugin#38]
Good Day Nutanix Team, 

I've followed the instructions on your readme as well as your site here https://portal.nutanix.com/page/documents/details?targetId=CSI-Volume-Driver-v2_3:CSI-Volume-Driver-v2_3

My current cluster is running on RHCOS, not sure if I can satisfy the requirements for iscsi-initiator-utils.

The issue im facing seems to be pretty common, volume mounts time out.

![Screenshot 2021-05-24 at 09 13 09](https://user-images.githubusercontent.com/48943204/119319295-8b0f4d80-bc7a-11eb-8aba-e22af511d623.png)

Please advise.

**Comment by tuxtof** [comment]
Hello @ccaprusu 
Can you check if Iscsid is correctly running on your Rhcos node , there is Redhat bug actually who failed to start it when you restart yours nodes

**Comment by tuxtof** [comment]
Another remark if you plan to run it against OpenShift 
The SCC part is missing of this repo actually.
You can solve it manually or use the Nutanix CSI Helm Chart who works perfectly with OpenShift 4.
A Dedicated OpenShift Operator is also coming soon ( in beta actually)

**Comment by ccaprusu** [comment]
@tuxtof thank you for getting back to me. I appreciate your time and help!

I have applied the SCC from the Helm git repo. In addition I read about the iscsid issue red hat bug. I was able to start iscsid on my worker nodes. However still getting the same error when a new pod was spun up.

Please advise.

**Comment by tuxtof** [comment]
Can you check log from each csi pod and Kubelet from the node running the pod
Don't hesitate to open a support ticket they can help too
I'm a little bit off the grid this week

**Comment by tuxtof** [comment]
Hello @ccaprusu , what is the status ?

**Comment by ccaprusu** [comment]
Engaged Nutanix Support, the tarball on Nutanix portal had some discrepancies. Ended up redeploying directly from the https://github.com/nutanix/csi-plugin/tree/master/deploy. All is working as intended now.

**Comment by tuxtof** [comment]
Wonderfull good news

Enjoy
