### ISSUE TITLE
CustomResourceDefinition v1beta1 error on OpenShift 4.9 / Kubernetes 1.22

### ISSUE THREAD

**Issue by tdc-bradr** [nutanix/csi-plugin#43]
Hi all,

I've just attempted to install the Nutanix CSI Operator from the Red Hat source on a fresh OCP 4.9 cluster.

I receive the following error when creating the NutanixCsiStorage instance:
`failed to install release: failed to install CRD crds/snapshot.storage.k8s.io_volumesnapshotclasses.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"`

I believe this has come about due to Kubernetes 1.22 (included in OCP 4.9) removing the deprecated 'v1beta1' version of CustomResourceDefinition. As far as I understand, 'v1' should be used instead.

I'm still quite new to the platform overall and trying to wrap my head around everything, but are there any plans to make this spec adjustment, or is there an alternative way to resolve this? Cheers!

**Comment by tuxtof** [comment]
Hello @tdc-bradr 

Our CSI driver is not yet supported with Openshift 4.9 and K8s 1.22, we are working actively on it.

Stay tuned and thanks for your support.

**Comment by tdc-bradr** [comment]
Hi @tuxtof 

Ah great, thanks very much for the update. I'll keep an eye out for an updated release in future.

FWIW, I had previously installed the driver manually on an OKD 4.7 cluster, and found it worked really nicely. We're just moving over to OCP proper, so we'll stick with an earlier release for the time being.

Cheers!

**Comment by tuxtof** [comment]
fix with Nutanix CSI operator v2.4.3 (release date nov 27th 2021)
