### ISSUE TITLE
Can CSI get snapshot PVC on Nutanix Files?

### ISSUE THREAD

**Issue by centrair-hoya** [nutanix/csi-plugin#47]
- K8s 1.22.3
- CSI Driver 2.4.1

I tried to get VolumeSnapshot for PVC on Nutanix Files(StorateClass acs-afs), It stuck pending and get message:
`Failed to create snapshot content with error snapshot controller failed to (PVC name) on API server: Operation cannot be fullfiled on persistentvolumeclaims "(PVC name)": the object has been modified; please apply your changes to the latest version and try again`

On Docs, I cannot find any comment for snapshot PVC on Nutanix Files.

**Comment by tuxtof** [comment]
Hello @centrair-hoya 
Snapshot is only supported with volumes based PV for the moment

**Comment by centrair-hoya** [comment]
@tuxtof Thanks a lot.
