### ISSUE TITLE
Proposal - use default target settings in /etc/iscsi/nodes/<tartget>/.../default

### ISSUE THREAD

**Issue by tonyfahrion** [nutanix/csi-plugin#49]
Currently the target specific default configuration is empty. This means Nutanix CSI depends on the iSCSI hosts global iSCSI configuration.

This is fine if we have fine control about the nodes setup process and only use the Nutanix CSI. But it can be a conflict if there is the need for an additional iSCSI provider on the same node. Trident is leveraging the target specific default config file to apply its best practice settings.

I think it will make the user experience with the CSI plugin much more convenient if the Nutanix CSI is aware of it's own iSCSI best practices https://portal.nutanix.com/page/documents/solutions/details?targetId=BP-2105-Linux-on-AHV:top-nutanix-volumes.html and sets those automatically. This will also make it possible to have different target settings for different providers.

This is especially useful for the `fast_io_fail_tmo = 120` and command queuing settings as their missing will show up once there is a maintenance on the Nutanix nodes.

Keep up the good work 💪

**Comment by tuxtof** [comment]
Thanks @tonyfahrion for this very interesting comments
I raised it to ENG @subodh01

**Comment by subodh01** [comment]
Thanks for your suggestions, we will look into implementing it in future CSI releases.

**Comment by subodh01** [comment]
We do use target specific default configuration file. The location of the file is /var/lib/iscsi/nodes/\<target-iqn>/\<portal>/default in my Centos VM. However, you are right that we are not setting Nutanix recommended defaults. We will address this in the future release.
