### ISSUE TITLE
Version 2.5.1 release

### ISSUE THREAD

**Issue by tonyfahrion** [nutanix/csi-plugin#51]
I think version 2.5 & 2.5.1 is missing on Github so far, but already released?

https://portal.nutanix.com/page/documents/details?targetId=CSI-Volume-Driver-v2_5:CSI-Volume-Driver-v2_5

**Comment by tuxtof** [comment]
Hi @tonyfahrion 

new repo is here https://github.com/nutanix/helm/tree/master/charts/nutanix-csi-storage

as stated in the doc you link

**Comment by tonyfahrion** [comment]
Ah I missed this, sorry! Thank you :)

**Comment by tuxtof** [comment]
no problem, this repo was here before helm become the default install method
