### ISSUE TITLE
Inquire about Volume Expans

### ISSUE THREAD

**Issue by ghost** [nutanix/csi-plugin#6]
Now I using CSI "driver: com.nutanix.csi" form Document CSI-Volume-Driver-v10
I want to expansion pvc in k8s cluster

k8s verion = 1.14.6

when i cmd > kubectl describe pvc claim1
error msg == Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.

![image](https://user-images.githubusercontent.com/46512530/65684324-8f402d80-e089-11e9-9614-0eaee361d5fc.png)

**Comment by subodh01** [comment]
Nutanix CSI driver does not support volume expansion yet. Support for this will come in next release which is currently scheduled for Oct End.

**Comment by ghost** [comment]
Thank you for your reply.

**Comment by subodh01** [comment]
Nutanix CSI driver v1.1.0 supports volume expansion.
